baseURL: https://devopsapalooza.com/
languageCode: en-us
title: DevOps-A-Palooza
googleAnalytics: G-CQRWJ8H090

taxonomies:
  tag: tags

permalinks:
  post: /:filename/

# See https://feathericons.com/
# The value of pre is the icon name
menu:
  nav:
  - name: Home
    pre: home
    url: /
    weight: 1
  - name: Developer
    pre: code
    url: /developer/
    weight: 2
  - name: SRE
    pre: cloud-lightning
    url: /sre/
    weight: 3
  - name: Architect
    pre: layers
    url: /architect/
    weight: 4
  - name: Consultant
    pre: briefcase
    url: /consultant/
    weight: 5
  - name: Tags
    pre: hash
    url: /tags/
    weight: 6

params:
  includeBootstrapJs: true
  showActiveNav: true
  dateFormat: Jan 2, 2006
  footerText: Made with [Hugo](https://gohugo.io/) & [Vanilla](https://github.com/zwbetz-gh/vanilla-bootstrap-hugo-theme)
  hideFooter: false

markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: true
      strikethrough: true
      table: true
      taskList: true
      typographer: true
    parser:
      attribute: true
      autoHeadingID: true
    renderer:
      hardWraps: false
      unsafe: true
      xHTML: false
  highlight:
    codeFences: true
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    style: monokai
    tabWidth: 4
  tableOfContents:
    endLevel: 6
    startLevel: 2
